### ISSUE TITLE
Ponzu + Buffalo

### ISSUE THREAD

**Issue by fbaube** [ponzu-cms/ponzu#105]
The Ponzu/Buffalo video did not cover its original agenda.

Can we expect that info soon ? I ask cos Buffalo does look very interesting.

Ponzu and Buffalo use different databases; do they play nicely together ?

**Comment by nilslice** [comment]
Hi @fbaube - 

A family emergency prevented the original presenter (@bketelsen) from teaching the course, so I stepped in to do a "light" version of the class. I have not used Buffalo, but Brian has and even wrote a neat generator for caching Ponzu data responses in a Go app: [ponzigen](https://github.com/bketelsen/ponzigen). This is the stack for the GopherCon site.

I believe you can think of Buffalo as the "front end" - designating routes, managing page templates, etc. You can use it for storing data in a SQL database as well, but if you want to use Ponzu's CMS, treat Ponzu as the main content datastore, and fetch the data via the [Content API](https://github.com/ponzu-cms/ponzu/wiki/API) into the MVC flow of Buffalo. Since recording the video you mentioned, there have been several updates to Ponzu which enable full server application development, not just fetching the data from the CMS - issue all CRUD commands from API clients via the new `api.Creatable`, `api.Deleteable`, and `api.Updateable` interfaces. All of which could be accessed via a client app, such as on created with Buffalo.

You  can treat Ponzu as a database and CMS for *anything* that speaks http though, so it could be the back end for you iOS apps, smart TV apps, JS web app, etc. Buffalo included!

I don't plan to do a video about Ponzu + Buffalo, but I'd like to see one! I do intend to release a few videos highlighting more of Ponzu-specific features in the future though, so who knows -- maybe there will be something related to Buffalo if I get around to trying it out.

Steve

**Comment by fbaube** [comment]
I was hoping for a cookbok presentation that would take me from zero to Ponzu-Buffalo integration in 60 minutes or less .. but that might be too much to hope for, if there is an impedance mismatch.
