### ISSUE TITLE
Handle complex layouts

### ISSUE THREAD

**Issue by parzival86** [ponzu-cms/ponzu#134]
Hey, I'm looking to migrate from WordPress (with the Advanced Custom Fields plugin) to Ponzu, currently my field types differ from page to page and are almost never the same across 2 pages. Do you have any ideas how to support this type of pattern? Is there a way to specify different fields per item? Or worst case an item type which can only ever have one entry?

**Comment by nilslice** [comment]
Hi @parzival86 - 

Based on what I know about ACF in WordPress, specifically in the context of a "Page", you're trying to define fairly static data in your layout from the CMS. Is that accurate? 

Since Ponzu does not concern itself with the layout of any client (website, app, etc), there isn't an out-of-the-box solution to this. What I have done to circumvent this, is to create a Layout Type for each "page" you want to specify on the front-end. These "Layout Types" are just content types, but meant to only have a single record which is edited over time. 

If you have 5 page templates in WordPress and an ACF type for each, you'll need to create 5 different Layout Types. For example: 

```bash
$ ponzu gen content homepage_layout title:string intro:string cta_text:string cta_url:string hero_image:string:file body:string:richtext
```

Then you could create a `HomepageLayout` content item in the CMS, fill it with your data, and reference it in your client-side code via its API endpoint (either via ID or Slug).

If the content on these "pages" isn't edited very often though, it would make more sense to have the content in the page be static along with your front-end code. 

For clarification: on the front-end, are you going to use PHP and make HTTP calls to your Ponzu API, or some kind of a Javascript SPA?


Thanks!
Steve

**Comment by parzival86** [comment]
Hi Steve,

Thanks for getting back to me so quickly! To cut a long story short my API will be digested by another Go server.

This solution is actually kinda perfect because it would allow you to easily incorporate A/B tests for different versions of a page as well should you need to.

I'll go ahead and run a prototype using this method and let you know how I get on but for now thanks for the concise answer and fast reply.

**Comment by nilslice** [comment]
Awesome, glad it helped! Very cool idea to do A/B testing by adding a new item. Please do let me know how your project goes and if you need help or clarification.
