### ISSUE TITLE
add chi pckg

### ISSUE THREAD

**Issue by kuronyago** [ponzu-cms/ponzu#145]
Good day, thank you for ponzu and sorry for the stupid question, but how to correctly implement "github.com/pressly/chi" for non /admin /api pages?

**Comment by nilslice** [comment]
@kuronyago - since that package requires that it's own Mux is used, vs. the default serve mux used by Ponzu, that you can only use it if you run two HTTP servers on different ports. One on `8080` (Ponzu by default) and one on `3000` (Chi's example) for Chi to listen on.

You can add HTTP handlers/routes in Ponzu by working directly with the `net/http` package. For example, in any of your Content type files, you could add to the `func init() {}`:

```go
http.HandleFunc("/", func(res http.ResponseWriter, req *http.Request) {
        res.Write([]byte("Hello")
})
```

If you need the additional router package, I would suggest building these in two separate processes: 
1. your Ponzu CMS - treat this like your database/backend and run it standalone
2. your Chi web application - treat this like your client/frontend and run it standalone

The two communicate over HTTP using GET/POST requests to the various [Ponzu APIs](https://docs.ponzu-cms.org/HTTP-APIs/Content/) (link is to Content API, but also see Search and File Metadata).  Or, you can use a work in progress Go client package: https://github.com/ponzu-cms/go-client

With the Go client, the pressly/chi example becomes:

```go
package main

import (
	"net/http"
        "fmt"

	"github.com/pressly/chi"
        "github.com/ponzu-cms/go-client"
)

func main() {
        // configure the http client
        cfg := client.Config{
            Host:         "http://localhost:8080",
            DisableCache: false, // defaults to false, here for documentation
        }

        ponzu := client.New(cfg)

	r := chi.NewRouter()
	r.Get("/news/:slug", func(w http.ResponseWriter, r *http.Request) {
                slug := chi.URLParam(r, "slug")
                resp, err := ponzu.ContentBySlug(slug)
		if err != nil {
                    fmt.Println(err)
                    http.Error(res, "Error", http.StatusInternalServerError)
                }

                w.Write(resp.JSON)
	})

	http.ListenAndServe(":3000", r)
}
```

You would have your Ponzu system running on its own, and the Chi web app on its own.

**Comment by nilslice** [comment]
Also, keep in mind that since your Ponzu Content types are exported Go structs, you can import your Ponzu project's `content` package into your Chi application and Unmarshal the `resp.JSON` (seen above) into any content struct you have made. 

The [`resp`](https://github.com/ponzu-cms/go-client/blob/master/client.go#L24) also has a `resp.Data` which is a `map[string]interface{}` which you can easily pass to go templates if you're writing HTML or other client presentation code.

**Comment by kuronyago** [comment]
thanks for the detailed explanation, keep up the good work!
