### ISSUE TITLE
Search book by author

### ISSUE THREAD

**Issue by excentro123** [ponzu-cms/ponzu#152]
Hello.
In tutorial video how can i search book by author?
thanks

**Comment by nilslice** [comment]
I would implement full text search by using the `search.Searchable` interface. The documentation is here https://docs.ponzu-cms.org/Interfaces/Search/

Since the author is not embedded in the book data, you will probably need to modify the SearchMapping or it might be easier to include some of the data (like the Authors name or anything else you'd like to search by) as a new field in Book.

Since Ponzu doesn't use a relational DB this is where the references start to fall a bit short, but with full text search you can typically find a solution.

**Comment by excentro123** [comment]
Thanks

**Comment by nilslice** [comment]
To make a search query for your books, use the Search HTTP API https://docs.ponzu-cms.org/HTTP-APIs/Search/

You can make a field-specific query too. If you do decide to embed the authors name in each book as a field called AuthorName (with json tag "author_name"), then in the http call to search endpoint, add a field scope like this:

`http://localhost:8080/api/contents/search?q=author_name:Hawking`

More info on search queries can be found here at the documentation for Bleve, the search engine Ponzu uses:
http://www.blevesearch.com/docs/Query-String-Query/

**Comment by excentro123** [comment]
Thank you very much

**Comment by nilslice** [comment]
You may already be doing this, but if anyone else finds this issue from searching Google, you can easily add data to your Content types without requiring a UI input for the editor. In the example of the embedded Author name in a Book, rather than creating a CMS input for the Book's new AuthorName field, you could instead use a Hook from the item.Hookable interface. The documentation for Hooks is here: https://docs.ponzu-cms.org/Interfaces/Item/#itemhookable

For example, by adding your own `BeforeSave` method to your Book type, you can get the referenced Author data and set the `author.Name` value to the request `PostForm` so the data gets passed to the HTTP handler and is then saved to the database. This way before any Book item is saved, the embedded AuthorName will always be in sync with Author referenced. However, if you change your author data you need to write some kind of update routine so that all Books which reference the Author will have the latest author name embedded.
