### ISSUE TITLE
addons disable search

### ISSUE THREAD

**Issue by guycalledseven** [ponzu-cms/ponzu#153]
Hi! I played with addons last night and I think I found a bug in the process.

If fbcheduler addon (or any custom addon which registers it self to CMS)  is enabled, search functionality stops working (it returns 404 not found header) on both http and https:

```
curl -I "http://localhost:8080/api/search?type=Book&q=test"
HTTP/1.1 404 Not Found
Access-Control-Allow-Headers: Accept, Authorization, Content-Type
Access-Control-Allow-Origin: *
Cache-Control: max-age=2592000, public
Etag: MTQ5NjA0NTk3Mg==
Date: Mon, 29 May 2017 08:20:05 GMT
Content-Type: text/plain; charset=utf-8
```
I enabled the addon by importing fbschedule in one of my content types  (`content/book.go`)

```
import (
       ...
	_ "github.com/bosssauce/fbscheduler"
       ...
)
```

I pinpointed the issue to addon.Register function. If function call is removed - search works.
`var _ = addon.Register(meta, func() interface{} { return new(PostScheduler) })`

After removing addon.Register, I can see addon in admin panel but if clicked, it returns 404:
`2017/05/29 10:38:00 Addon:  it.bosssauce.FacebookScheduler is not found in addon.Types map`

I stopped digging and decided to ask here. What am I doing wrong?

Thanks in advance!

**Comment by nilslice** [comment]
Hi, thank you for the detailed report. It sounds like this is a bug. I'm traveling today and on an American holiday so it's unlikely that I'll be able to look into it closely until late tonight or tomorrow (pacific time). If you're interested in digging further, please do and let me know what you find. 

A couple questions:

1. Are there any errors logged when you try to make the Search request?

2. Did you disable the Addon before removing the Register function (by clicking the disable button in the Admin UI)? Does is break search when enabled and disabled through the Admin UI?

3. What does your content type code look like? If you can share it please do. 

Sorry for the trouble with this.. and thanks again for submitting an issue. I will try to reproduce it ASAP.

**Comment by guycalledseven** [comment]
Hi @nilslice not a trouble at all, except I am not familiar that much with ponzu addons internals (design decisions and such). I am having hard time interpreting them without docs (eg. can't understand why is addon added to system.db / __addons first time it's compiled instead when it's enabled in cms?).

As for questions:

1. There are no errors of any kind.
2. This happens no matter if addon is enabled or disabled (frankly I have no idea what enable-disable does since it seems to me that addon works  in both status modes).
3. This is easy reproducable with fbschedule example. My own content type is in the works so don't have anything to share yet. :)

**Comment by nilslice** [comment]
@guycalledseven - Yes, sorry about the docs -- there would be more if I were more certain of the APIs. Its helpful to get feedback from others like this..

> can't understand why is addon added to system.db / __addons first time it's compiled instead when it's enabled in cms?

Mostly, this is so the developer installing the addon faces any compile-time errors with naming collisions or other possible problems before the CMS is shipped to an end-user. Enable / Disable are control features for the end-user, and allow the addon to have a better idea of its state. If you have suggestions as to how this could be improved, please let me know (keeping in mind that 2 different types of users are impacted: the developer and the admin/end-user).

> 1. There are no errors of any kind.

Ok, thank you.. there probably should be then ;) I'll see if I can find out where this is happening in the http handler for search. It does throw 404s but hard to tell where without logging.

> 2. This happens no matter if addon is enabled or disabled (frankly I have no idea what enable-disable does since it seems to me that addon works in both status modes. looking at the code it looks like status is only referenced from admin).

Ok, good to know. To clarify, Enable / Disable are control features for the end-user. The developer of the addon can be respectful of this user control in their addon implementation so that any procedure is not run if the addon is in a Disabled state. 

> 3. This is easy reproducable with fbschedule example. My own content type is in the works so don't have anything to share yet. :)

Ok, and are you using the default mapping in the Searchable implementation? Probably unrelated, but good to have as much info as possible. 

Thanks!

**Comment by guycalledseven** [comment]
@nilslice Thanks for taking time to look into this. Also, I have been lurking ponzo for some time now and I think basic API is solid.  👍 

Regarding addons, I would be interested in seeing more internal stuff exported (eg. for building json output, just like api.Record, api.CORS, api.Gzip).

Also, I see that enabled/disabled in CMS could work only for addons that
- extend the API with eg. new endpoints (what can be publicly viewed)
- extend the admin with eg. new CMS modules
- something event driven (like fbschedule) 
- or something standalone (eg. cron jobs of some kind, something that alters default functionality (eg. override all routes, change language of admin)

I do not see this working with Content form type addons such is reference, since data is already in bolt.

Regarding issue in hand - is it possible to defer initialisation of addons, eg. after system has been set up? 

if I am reading my log correctly - there is race condition between who will Init bolt db.store - addon checker or system. Addon wins, but it fails to set it up it correctly.  

In `ponzu/system/db/addon.go`, addon initialises boltdb in order to check for _addons___ before the system sets up bolt store.

```
func AddonExists(key string) bool {
	var exists bool
	if store == nil {
		Init()
	}
       ...
```

When addon initialises db, item.Types is empty, so goroutine cannot loop over and set  search.MapIndex(t]. In order for search to work search.MapIndex is needed for Search[typeName] = idx to be set in `ponzu/system/search/search.go`. 

When system Init is invoked with correct item.Types available, init exits since, store != nil.

```
func Init() {
	if store != nil {
		return
	}
...
}
```

We get 404 because search is in semi setup state (doesn't know content types?), so  search.TypeQuery in `system/api/search.go` returns 'not found return No search index found for type provided'.

```
	matches, err := search.TypeQuery(t, q)
	if err == search.ErrNoIndex {
		res.WriteHeader(http.StatusNotFound)
		return
	}
```

Hope I got this right. :)
Best

**Comment by nilslice** [comment]
@guycalledseven 

>  Thanks for taking time to look into this. Also, I have been lurking ponzo for some time now and I think basic API is solid. 

Well, thank you for saying so and for now being involved in the project -- I definitely cannot do it all alone and we've had some great contributions from others. I'd love to add you to the list!

> Regarding addons, I would be interested in seeing more internal stuff exported (eg. for building json output, just like api.Record, api.CORS, api.Gzip).

Anything you would like exported, please feel free to do so and submit a PR. If something isn't exported, it's typically because I didn't need it outside its package, but I'm not against broadening the public APIs. If you do export something, it might be best to wrap the unexported func in a new exported one, so the internal code doesn't need to change. For example, add somewhere (not real code):

```
func FmtJSON(data []byte) []byte {
        fmtJson(data)
}
```

> Regarding issue in hand - is it possible to defer initialisation of addons, eg. after system has been set up?

This is tough because of the import sequence. Initialization process imports content, before the system adds all the content types to the item.Types map, some content file imports an addon, the addon sets up its own initialization (like you mention with `__addons`), which, as you also point out, falsely passes the system.Init() which thinks the `store != nil`.. Hm...

It looks like you have uncovered it, your findings do explain why the search map index wouldn't be set, thus throwing the 404. It's even worse, that the search indexes aren't set and no content is being indexed.. 

I don't currently have a solution for this, since it is the way Go packages work (and all Addons are Go packages). I tried many different ways to try and force content to be initialized prior to addons, but got a cyclical import in all of them, but I'm sure I've left out some. 

Any ideas? Thank you very much for digging in here, really appreciate it!

**Comment by guycalledseven** [comment]
@nilslice ah yes, this is classic lazy initialisation singleton thread safety issue. 

Don't think using channels or sync / mutex can do here any good without complete rewrite because of timing when db.Init is called via addon.Register (in package variable definition which happen AFAIK before any init())

```
var _ = addon.Register(meta, func() interface{} { return new(Checkin) })
```

I think that "only" issue here is with `item.Types` not being populated for search db.SortContent() to be executed.

I changed logic of search initialisation a bit:  I moved goroutine out of `db.Init()` into `cmd/ponzu/main.go` and it seems that search is working and that I did not break anything.

I can try to submit PR, however since there are no tests, I am not sure how this fix will work for everybody nor that is idiomatic (it's better than `time.Sleep(1)`  ) :)

**Comment by nilslice** [comment]
You're right, without totally re-writing were at the mercy of the Go tooling.. nothing we can control with code besides moving the initialization. 

If you could submit a PR, I'll run through the manual testing (which as you can see doesn't catch everything 😬) - and will smooth out any rough edges if any are in there. 

Thank you!

**Comment by nilslice** [comment]
@guycalledseven - hey, would you mind sharing the fix you came up with for this? if you don't want to do a full PR, no worries - even just a copy/paste of the pertinent files would be quite helpful. 

Thank you,
Steve

**Comment by guycalledseven** [comment]
@nilslice just did PR #157 please comment.

Since there is no guarantee `Item.Types` is populated even when indexer is called from `main()`, as a possible upgrade I see retrying `InitSearchIndex` call or introducing "sync" package all over ...  or not using `init()`.

ps.I spent numerous hours trying to test build from local (non git commited copy) and failed. `ponzu new` would be great to have option to use local copy (similar to `--fork`).

**Comment by nilslice** [comment]
Thank you very much for your help with this, @guycalledseven -- really appreciate it!

**Comment by guycalledseven** [comment]
Glad I could help,  wish it was something more than reshuffling some code. ;) 
I have some other cms addon ideas which I will try to pursue and commit some PR's when time allows me. :)

**Comment by nilslice** [comment]
Every PR is an important PR! Looking forward to collaborating more with you in the future :)

**Comment by nilslice** [comment]
> ps.I spent numerous hours trying to test build from local (non git commited copy) and failed. ponzu new would be great to have option to use local copy (similar to --fork).

Sorry, I didn't notice this comment from earlier.. I completely agree, it can be painful. I haven't tested it, but possibly running `ponzu upgrade` in a test project could work, after you make changes to your local branch.

I have a couple other ideas that I'd need to test out. but I'll add this to the top of my list and see to it that there is progress made by the end of the week! thanks for pointing this out.
