### ISSUE TITLE
Feature Request: Bind to IP

### ISSUE THREAD

**Issue by webeau** [ponzu-cms/ponzu#177]
I was wondering if there is any way to support binding to a particular IP address or if you might be able to address that in a future release?  I have multiple domains on a single dedicated server with 16 individual addresses.  It appears that Ponzu will listen to all addresses on the HTTPS port.  Thanks!

**Comment by nilslice** [comment]
We definitely should support this - and I can try to get it added this weekend. 

Would another CLI flag paired with the `run` command suit your needs?

**Comment by webeau** [comment]
Are you kidding? YES.  Right now that's my biggest limitation to implementing Ponzu.  Whenever you are able to get to it, please know it will be very much appreciated!

**Comment by nilslice** [comment]
Sure thing! I'll ping you here once I have it complete. Out of curiosity, would you be able to share a bit about:

1. how you found Ponzu
2. what you're building
3. the deployment / hosting environment you're running

Feedback like this is super helpful to make it a better product & dev experience.

Thanks,
Steve

**Comment by webeau** [comment]
I have been searching for headless cms for sometime.  I have not been satisfied with the shoehorning of established CMS' into this area.  I also believe that website development should be moving towards application-based designs.  So I basically found Ponzu through Google.

My interest is two-fold:  I have need of an API interface for a small chain of movie theatres where imdb/tmdb solutions for information is overkill and limits the owners ability to customize the results.  

Second, I would like to build a frontend framework that could take information from Ponzu and generate complete web applications using Angular. 

Currently I use NGHTTPX as a reverse proxy to Nginx.  Why?  Because of its HTTP/2 Push ability that Nginx still lacks (among other reasons).  My server is an OVH dedicated server with 64gb a 2TB raid array and modern processor (forgot the nomenclature right now). 

I was also curious about the References add-on for Ponzu.  It reminds me of JSON-LD on the surface (I haven't had a chance to dive deeply into it). 

Thanks, again, for your prompt response.  I was stunned by the speed with which you responded!

**Comment by nilslice** [comment]
Hey @webeau - 

This is now available in the `master` branch. You can get it by running `$ go get -u github.com/ponzu-cms/ponzu/...` and then from inside your projects, you can run `$ ponzu upgrade` to make sure each project has the latest core code. 

Let me know if this works for you. The new `--bind` option for the CLI `run` command is documented here: https://docs.ponzu-cms.org/CLI/General-Usage/#run

Thank you for the feedback -- that sounds like a great set up and I think Ponzu would be a perfectly suitable option for your CMS / API needs. If you need any other help or have other thoughts about Ponzu, feel free to file another issue or chat with the community on slack on the #ponzu channel at https://gophers.slack.com/messages/C3TBV356D/ 

I had not seen JSON-LD before, but you are right - the references concept in Ponzu is very similar! I think the added bonus of Ponzu's architecture is that since the JSON responses reference same-origin data URIs, you can easily push them down with HTTP/2 Server Push. You probably already saw Ponzu's Server Push integration, but if not, it's as easy as adding a `Push()` method to your Content types. Here are the docs for that: https://docs.ponzu-cms.org/Interfaces/Item/#itempushable

**Comment by nilslice** [comment]
> Second, I would like to build a frontend framework that could take information from Ponzu and generate complete web applications using Angular.

If you get around to starting this, please let me know -- I'd love to see if I could help or at least follow along :) You might find @natdm's [Typewriter](https://github.com/natdm/typewriter) project interesting since it helps sync your Go content types (data models) with your front-end code. There is an [example](https://github.com/natdm/typewriter/blob/95b5ec8cb27f05525e10e4f9a1fe5e912f678539/EXAMPLES.md#example-use-in-a-package-like-ponzu) using Ponzu.
