### ISSUE TITLE
API requests not working

### ISSUE THREAD

**Issue by MeStrak** [ponzu-cms/ponzu#247]
After getting Ponzu up and running I've been following the YouTube walkthrough. Unfortunately I can't get any API requests to work either through Chrome or Postman. I always get a 400 error.

For example when I try a basic content request for a content type called experiment that I created.

localhost:8080/api/content?type=experiment&id=1

Returns a 400 error. Is there a setting I missed and need to turn on somewhere?

**Comment by nilslice** [comment]
localhost:8080/api/content?type=**experiment**&id=1

`experiment` is likely the issue. You need to use the exact string name of your content type, which should be `Experiment` (capitalized) since the type must be exported from your program's content package. If you are unfamiliar with this, take a look at this article: https://medium.com/golangspec/exported-identifiers-in-go-518e93cc98af

**Comment by nilslice** [comment]
Hi @MeStrak - 

Were you able to solve this problem? If not, please open a new issue. Thanks!
