### ISSUE TITLE
Basic questions

### ISSUE THREAD

**Issue by MeStrak** [ponzu-cms/ponzu#248]
While I'm still coming up to speed I have a few questions about the basic functionality of Ponzu. I was originally planning to use Bolt as the CMS to store content for my app, but am now looking at Ponzu because there's no official API for Bolt. Most of my questions are related to things that were pretty easy in Bolt.

Can content items have versions? For example to restore a previous version of a specific content item, or to schedule approval and publishing of an updated version of a content item on a specific date?

Is there an easy way to manage translation of content items into different languages? E.g have a content item where I can easily access the English and French versions of it from the admin UI.

For basic API authentication to ensure that not everyone who finds the web address can view or edit content - I assume the access add-on is what I need to use?

For repeated items is there any ordering? And can they be reordered easily? E.g. I have Procedure and ProcedureSteps content types. A Procedure contains several ProcedureSteps, and the order is important. If I select related ProcedureStep items when editing a Procedure item, are they returned in API requests in the order selected? If a mistake is made when selecting them, can the order be changed?

I know you say that Ponzu is super fast - are there any benchmarks published to show just how fast? (Might be a nice advertising feature on your site :) )

Any recommended (and cheap) go hosting providers? Is Google apps always free tier the most suitable?

Thanks!

**Comment by nilslice** [comment]
> Can content items have versions? For example to restore a previous version of a specific content item, or to schedule approval and publishing of an updated version of a content item on a specific date?

Currently, no, but this would be an awesome PR.

> Is there an easy way to manage translation of content items into different languages? E.g have a content item where I can easily access the English and French versions of it from the admin UI.

Also currently no, and would love to see this as a PR from the community 👍 

> For basic API authentication to ensure that not everyone who finds the web address can view or edit content - I assume the access add-on is what I need to use?

No one but your Admin users can edit content by default. You can implement the `api.Updateable` or `api.Createable` interfaces to enable outside requests to change/create content. There are other interfaces in the documentation (https://docs.ponzu-cms.org) which may help you as well. Yes, there is an addon available for protecting content items from outside requests w/o a JWT in the header or cookie, but it's fairly untested: https://github.com/bosssauce/access

Though, the functionality is something you could add yourself and customize to your exact needs.

> For repeated items is there any ordering? And can they be reordered easily? E.g. I have Procedure and ProcedureSteps content types. A Procedure contains several ProcedureSteps, and the order is important. If I select related ProcedureStep items when editing a Procedure item, are they returned in API requests in the order selected? If a mistake is made when selecting them, can the order be changed?

Repeated items are returned through the API in the exact order you have them listed in the CMS editor. 
They can be easily re-ordered through the UI, but it does require you to remove one and add it again -- the UX is not the best for re-ordering (another PR opportunity which would be great). 

> I know you say that Ponzu is super fast - are there any benchmarks published to show just how fast? (Might be a nice advertising feature on your site :) )

Only the `net/http` package is used for network request handling, so you can defer to the Go benchmarks of any popular technology publication on the topic. Additionally, since the data fetched by each API call is simply bytes on disk, mostly pre-processed and formatted for the response, there is practically no database latency you may find in other systems.

> Any recommended (and cheap) go hosting providers? Is Google apps always free tier the most suitable?

There really aren't "Go hosting providers" as your ponzu project will be compiled to a single static binary. You can put this binary on any system your build step targets (see https://dave.cheney.net/2015/08/22/cross-compilation-with-go-1-5). I would recommend running a $5/mo instance on Digital Ocean using a pre-configured Debian Linux distribution. There are many other options, but it is hard to make any recommendation without knowing how you intend to deploy your project.
