### ISSUE TITLE
Disable Cors not allowing requests

### ISSUE THREAD

**Issue by joshdstockdale** [ponzu-cms/ponzu#258]
Maybe I'm misunderstanding but I'm having a difficult time with the Disable CORS option but whenever I have Disable CORS checked along with Disable HTTP Cache on, unless my Domain Name is set to localhost, I get a 403 Access Denied Error. I'm under the impression that whatever my domain name is, that I should be able to access content via: https://example.com:10443/api/content?type=Song&id=1 or http://example.com:8080/api/content?type=Song&id=1

Again though, if I set my Domain name to localhost then everything works as expected. Is there anyway for me to get my domain to request via the api with an actual domain name?

(BTW, I love this project. Thank you so much for starting it and putting it up.)

**Comment by nilslice** [comment]
Hi @joshdstockdale  -

Can you provide a bit more info about how you are making the requests to your Ponzu server? If you disable CORS, your request must come from the same origin. For example, If you have a local dev JS client app running on something like `localhost:3000`, and your Ponzu server has a domain name configured to anything other than `localhost`, then you will get the 403. 

Thank you for the kind words, I'm glad you're finding it useful!

**Comment by joshdstockdale** [comment]
I’m just accessing it through the browser, literally typing it in the url bar, not through a front end app. If I use localhost for both the domain name on ponzu and in the request, than everything works. But if I use anything else, for example asdf.localhost or example.com for both the domain name on ponzu and the request, I get a 403 through the browser.

**Comment by nilslice** [comment]
Hi @joshdstockdale - 

My apologies, I'd like to help out more, but I currently have a pile of other tasks at hand to get through.

I would suggest taking a look at the code for the CORS implementation, here: https://github.com/ponzu-cms/ponzu/blob/master/system/api/cors.go#L19

If you find that there is a bug, please let me know or submit a PR. It's hard to tell exactly whats going on, since I assume you have some self-configured /ect/hosts or other mapping done locally. Some things to look at: 
- check to see what the `Origin` header is being sent from the request
- add some logging around the CORS code in Ponzu (edit the Ponzu core within your app at `$YOURPROJECT/cmd/ponzu/vendor/github.com/ponzu-cms/ponzu/system/api/...` and re-build)

Again, sorry I cannot be more helpful at the moment.

**Comment by joshdstockdale** [comment]
@nilslice 
All good. I'll dig into it and let you know if I find anything. Thanks for the direction.

**Comment by joshdstockdale** [comment]
I see. If you access the url just via a browser the origin header is not set. There's a line in your code that if the domain is localhost, then the origin is not needed, bc it is assumed to be for dev. This isn't a bug. BTW on a mac at least, if you use *.localhost it always resolves to 127.0.0.1 without changing your host file, just a little trick.
