### ISSUE TITLE
uploads folder is full of trash files

### ISSUE THREAD

**Issue by nanohard** [ponzu-cms/ponzu#261]
Whenever I create a content item I get an empty file in the `uploads` folder.
Why does this happen?
Is it possible to prevent this from happening so that only files > 0 bytes are put there?

Edit:
I have discovered that the filenames are timestamps. But why do they exists?

**Comment by nilslice** [comment]
Hey, it is definitely possible but would require a patch that I have not had time to PR. 

I'm not at my computer at the moment, but if you're interested in looking there's an upload.go file (I believe) where you'd likely check the byte length of the multipart fields and ignore anything that is == 0. 

I would like to change the API a bit before v1 so that only multipart encoded form requests even go down the path of an upload and enable create/update requests to be in any other encoding. That would be an awesome PR if you are interested...

**Comment by nanohard** [comment]
I could only implement a workaround to not show the zero-byte files in the GUI. I could not figure out how to get the files to not be uploaded.

I think in order to do this several functions will have to be split up. As it stands now, it seems like the functions in question will only write to the database if the file is uploaded. So- no file, no database entry. This means that content cannot be created without a timestamped file being created first, which needs to be split out of the functions and made to be a separate, optional, operation.

**Comment by nanohard** [comment]
Files and functions that are involved:

- `system/admin/handlers.go`
  - `editHandler()` (calls on `storeFiles()`)
- `system/admin/upload/upload.go`
  - `storeFiles()`

Perhaps, if `storeFiles()` is aptly named, then we can then just focus on `editHandler()` and split out the calls to `storeFiles()` to call on only if actually storing a file. I'll have to actually read the code.

**Comment by olliephillips** [comment]
Thought I would take a look at this, but I can not replicate this behaviour. Fixed already?  Anyone else see empty files created? I see folders, but not files.

**Comment by olliephillips** [comment]
Closing this on the basis that it is now old and I could not replicate - either with file or filerepeater. It may have been addressed. Please re-open if anyone finds this to still be an issue.
