### ISSUE TITLE
Add ponzu generate myfield:"xml"

### ISSUE THREAD

**Issue by fbaube** [ponzu-cms/ponzu#44]
This would add a new field type "`xml`". This could configure the field to use `editor.Richtext`, and install by default some additional markup-friendly editor features, plus the ability to specify XML validation.

I see that `nilslice/summernote` uses Codemirror(.net), so I guess Codemirror is used for ponzu richtext codeview mode (the "`<>`" button) ? So all the features & options that Codemirror offers are in principle available for ponzu richedit in codeview mode, and maybe in non-codeview mode too ?

**Comment by nilslice** [comment]
Hi @fbaube - 

Could you elaborate on how this would be used? Or, how does myfield:"string" and using the editor.Richtext doesn't already satisfy any requirements since you can put markup directly in the code view "<>", as you mentioned. You can add markup directly in the editor.Textarea function as well, but be mindful of how it is escaped. 

I don't know if _all_ the codemirror features/options are available, but if you test for a specific one and find that it is not available, let me know!

**Comment by fbaube** [comment]
I'm just thinking, specialised modes in editors always add nice functionalities. Codemirror has http://codemirror.net/mode/xml/ 

Schema-guided autocomplete is demo'd in https://codemirror.net/demo/xmlcomplete.html ; after you type "<" and select a tag, typing a space offers attributes.

I'd like to use this functionality for DITA. DITA has schemata in DTD, RNG, and XSD. 

Unfortunately I've never actually configured Codemirror myself, so I have no idea how to proceed....

**Comment by nilslice** [comment]
Hi @fbaube - sorry for the delay, I must've missed the notification. 

So just to be clear, you're looking to gain auto complete in the code view mode of the richtext editor?

I agree that this would be useful to add/edit markup, but I'm not as sure about adding a CLI specifier would be necessary. It should just be available in that mode by default IMO. 

Unfortunately, the codemirror configuration is likely buried within the "materialnote" library I use to instantiate the richtext editor, and I'm not as familiar with its codebase as I probably should be. I will take a look at it though and let you know what i find.

**Comment by fbaube** [comment]
Autocomplete is the most desirable feature add, altho Codemirror has other XML enhancements too. I skimmed the Materialnote website and yes, it's a layer of complication if the goal is to directly tinker with Codemirror. But anything you can discover would be great !  
I could provide a simplified version of the LwDITA DTD for testing purposes. The inline elements are much like HTML5; the block elements would be mostly new. There are additional attributes for things like links.

**Comment by nilslice** [comment]
Ok, thank you for clarification. I have added this as a suggested feature and will do my best to get it started. I created a [Community Suggested Features](https://github.com/ponzu-cms/ponzu/projects/2) project where I try to lay out a rough road map of whats to come, and what is in planning or development, so that anyone can come check out ideas to contribute if they would like. 

I would love to get a PR for this, since admittedly the XML stuff is a bit outside my domain. If you'd like to work on it, let me know and I'll happily help get you started.

Since this feature is added to the project above, I will close out this issue for the time being. Feel free to join the #ponzu slack channel in the Gophers organization here: https://invite.slack.golangbridge.org and we can discuss further. 

Thanks,
Steve

**Comment by fbaube** [comment]
DITA uses Relax NG for its master grammars, and specializations of DITA (which are encouraged) should be based on the RNG grammar. FWIW I found a codemirror derivative called "xmlmirror" ( https://lastlog.de/blog/posts/xmlmirror.html ) that claims to do schema-driven editing, including RNG-driven. Unfortunately xmlmirror's dependencies are very complex and it failed to install. But I'll keep looking around. 

(I avoid Slack cos IMHO infinitely scrolling chat interfaces are useless IRL. But I'll leave notes here on this issue.)

**Comment by nilslice** [comment]
Thanks! I will keep an eye on this too. I'm planning to dedicate more time over the next couple weeks to these types of issues.

**Comment by fbaube** [comment]
Now that I have found the RNGs for LwDITA (Lightweight DITA) I think I'll simply take a page in ponzu where the text edit widget works and then experiment with it until I get codemirror's XML functionality working.

**Comment by nilslice** [comment]
Sounds good. Let me know if you run into any issues -- I will admit, that code is a little messy :smile:
