### ISSUE TITLE
Make things more sortable

### ISSUE THREAD

**Issue by corylanou** [ponzu-cms/ponzu#48]
Currently, there isn't a good way to sort drop downs when selecting sub-content.

I'm starting this issue to have a discussion on prosed fixes.

I believe based on some conversation I've already had that it may make the most sense to add some sortable interfaces to this file:

https://github.com/ponzu-cms/ponzu/blob/master/system/item/item.go

I'm still getting acclimated with the code so any direction would be helpful, and I'm more than happy to make the changes.

**Comment by nilslice** [comment]
After discussing the use-case with @corylanou and consideration taken surrounding some possible issues with expected behavior between editor.Select and reference.Select, the current planned implementation to have alphabetically sorted select dropdowns is to do it in the CMS with javascript.

If anyone has thoughts on this, please share.
