### ISSUE TITLE
It support markdown?

### ISSUE THREAD

**Issue by fanux** [ponzu-cms/ponzu#70]
As I know it not support markdown currently.

And how can I visit my content after save it?

**Comment by nilslice** [comment]
Hi @fanux - 

It is possible to save markdown in an `editor.Textarea`, but you would need to render it in your client that consumes the JSON 

In order to get your content after it is saved, use the content API described here in the Wiki:
https://github.com/ponzu-cms/ponzu/wiki/API

I know there is at least one project using Markdown with Ponzu.. but I will need to remember which one and ask the owner if they can share their implementation.

**Comment by fanux** [comment]
OK, I got it,  hope to provide default client in the future.

**Comment by nilslice** [comment]
Glad to hear you got it working. Could I ask what you ended up doing for your markdown renderer? And what kind of JSON client did you use?

**Comment by fanux** [comment]
Render markdown on the front end is better. Maybe I need to develop my own client.
