### ISSUE TITLE
Error during the installation of Ponzu

### ISSUE THREAD

**Issue by arjanvaneersel** [ponzu-cms/ponzu#75]
I gave the installation command as stipulated on github: go get github.com/ponzu-cms/ponzu/...
and then get this error: go install runtime/internal/atomic: open /usr/local/go/pkg/linux_amd64/runtime/internal/atomic.a: permission denied

I checked all directory permissions on the path mentioned in the error and they seem the be ok, which is world reading rights. I'm using Go 1.8 on Debian. And my paths are set like this:
export GOPATH=/home/arjan/Development/Go
export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin

Is this a bug or am I doing something wrong?

**Comment by arjanvaneersel** [comment]
It seems that this issue is NOT related to ponzu. I just upgraded to 1.8 before installing ponzu. I'm getting this error in any of my projects. So it's a problem with my installation.

**Comment by nilslice** [comment]
Hi @arjanvaneersel - 

Sorry I didn't see this earlier. Thank you for reporting the issue, and updating it with your new findings. Hopefully you get the 1.8 install issue sorted out.. let me know if you don't and I can try to help, I use debian too.

I'd love to know how you're using Ponzu once you get it installed -- I noticed you also have a CMS project in Go! It would be great to have some more help on Ponzu, so if you find that any features you'd expect to have aren't present, feel free to open an issue and we can work on a new PR.

Thanks,
Steve

**Comment by arjanvaneersel** [comment]
I simply removed the whole Go directory and reinstalled 1.8 and everything works well again. I do have another issue, but I'll post that tomorrow if I can't fix it.

The CMS on my github is far from finished and mainly experimental. I did write a CMS in Python before, but because I made the switch to Go I started experimenting to eventually rewrite in Go, if I can't find an already existing solution.

I was looking at Ponzu to make a quick and simple website for the Go user group I'm trying to start here in Bulgaria.

I'd be happy to help out and contribute to Ponzu, I already saw a request regarding i18n, which is something my sites would also need. In my Python CMS I did create a solution for that. However before I can contribute I need to get used a bit to Ponzu and study a bit more on how it works exactly.

**Comment by nilslice** [comment]
That is great. Please do let me know if you can't fix the other issue and I'll do my best to help. Thank you for your help and if you find anything in the Ponzu core/internals that you have questions about, please let me know. 

Some advice while investigating data/content... use the [BoltGUI](https://github.com/nikitabokovoy/BoltGUI) command to inspect the database (content, config and addons are in `system.db` and the API analytics are in `analytics.db`).. I think it will help you see how a lot of the content types and their related buckets work since BoltDB is kind of a black box without a way to look inside by default.

Feel free to jump into #60 and add to the discussion whenever you're ready -- I don't have much experience doing i18n, so any help is appreciated.
