### ISSUE TITLE
Design folder to hold examples.

### ISSUE THREAD

**Issue by joeblew99** [ponzu-cms/ponzu#89]
i also think that a "design" folder is needed somewhere just like goa has.
This is used to hold the scripts and anything you need to generate examples so devs can quickly try stuff out. Maybe later this will evolve further in the way it works but for nwo this is what i started to do.

````

TARGET=$GOPATH/src/github.com/ponzu-cms/test01

# This is an example to show of the references Addon.
# Data Model is:
# 	- Channel
#		- Title (editor.Input)
#		- VideoRef[] (Addon.Reference.SelectRepeater)
#		- Rating (editor.Select)
#		- Tags (editor.Tags)
# 	- Video
#		- Title (editor.Input)
#		- VideoUrl (editor.Input)
#			- VideoThumbnail (Addon.Design.ThumbnailFromURL)
#		- Description (editor.Richtext)
#		- Rating (editor.Select)
#		- Contributor (reference.Select(ContributorType.Name))
# 	- Contributor
#		- Name (editor.Input)
#		- Picture (editor.File)
#		- Bio (editor.textarea)

# Delete DB
rm $TARGET/analytics.db
rm $TARGET/system.db


# Delete content types
rm -f $TARGET/content/*.*


# Copy Content Types
# There is NO Generate support for Addons (like a reference), so what would it look like ?
# For nwo just copy the hand coded ones in.
cp -R ./content $TARGET/


# Build
cd $TARGET
ponzu build
ponzu run

# Set Content (dont know how to do this)
# Either use the api.Externalable interface and add content via HTTP POSTs or
# see the `SetContent` function in the `system/db` package

# Get Content
# http://localhost:8080/api/content?slug=item-id-f2a84403-6b58-4709-95bd-c5591d910b21
# http://localhost:8080/api/contents?type=Channel

````

**Comment by nilslice** [comment]
Thanks for writing this out, @joeblew99 - I agree there should be more examples of code and process as part of the project. I wonder if it makes more sense to provide these in documentation though rather than inside the repository? 

I plan on releasing a full site & documentation pages for Ponzu once we hit a 1.0 (hopefully by end of March). This site would have all of the project details, a better Quickstart example, and other examples of projects and how-to's which I think would be a great place for the kind of thing you wrote. It would probably mirror some new repo like github.com/ponzu-cms/docs or github.com/ponzu-cms/examples (or both) so anyone could contribute these ideas. 

Do you think that there is significant benefit in putting these kinds of files directly into the project source, versus on an external documentation site?

P.S. I made some minor edits to the script you shared, so in case someone were to see this via Google search or something it was all correct.

**Comment by joeblew99** [comment]
I would put the setup scripts in the same repo for core examples that show of step by step the techniques.
There is nothing preventing others from making examples too in other repos.
I found it very easy.
I was tempted to make it a proper DSL like goa a bit, but just found it fine for now to make a .sh script. 
You could also make it a golang script too. 

Yeah i realised later i had a few boo boohs :)

**Comment by nilslice** [comment]
@joeblew99 - thanks for your patience on this issue.. finally launching my project tonight so the dust has started to settle :)

Check out the latest master branch.. Do you want to go ahead and put your PR together for the `examples` directory? Within the examples directory, there should be a directory for each "example", but examples shouldn't be full Ponzu projects.. just a few files with a README.md explaining what the example is demonstrating. I will add an example of implementing the `api.Externalable` interface (which I am planning to rename), and expect that with more major community contributions, an example is part of their PR.

I also added a README.md to the root `examples` directory so people are aware of what to expect from them... also, a LICENSE file to include the same BSD-3 license so example code can be used as freely as Ponzu core. 

Thanks!

**Comment by nilslice** [comment]
~ #97 adds this
